# -*- coding: utf-8 -*-
import os
import re
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

logger = logging.getLogger(__name__)


def _to_html(content):
    """Convert investor insights markdown-like syntax to HTML body."""
    h = content

    # Headers
    h = re.sub(r'^### (.+)$', r'<h3>\1</h3>', h, flags=re.MULTILINE)
    h = re.sub(r'^## (.+)$', r'<h2>\1</h2>', h, flags=re.MULTILINE)

    # Bold
    h = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', h)

    # Special boxes
    h = re.sub(r'\[WARNING\]([\s\S]*?)\[/WARNING\]',
               r'<div class="box-warning">\1</div>', h)
    h = re.sub(r'\[HIGHLIGHT\]([\s\S]*?)\[/HIGHLIGHT\]',
               r'<div class="box-highlight">\1</div>', h)
    h = re.sub(r'\[SUCCESS\]([\s\S]*?)\[/SUCCESS\]',
               r'<div class="box-success">\1</div>', h)

    # Lists
    h = re.sub(r'^- (.+)$', r'<li>\1</li>', h, flags=re.MULTILINE)
    h = re.sub(r'(<li>.*?</li>\n?)+', r'<ul>\g<0></ul>', h, flags=re.DOTALL)

    # Paragraphs / line breaks
    h = re.sub(r'\n\n', '</p><p>', h)
    h = re.sub(r'\n', '<br>', h)
    return f'<p>{h}</p>'


def build_html_email(content, generated_at=None):
    """Wrap investor insights content in a styled HTML email."""
    date_str = ''
    if generated_at:
        try:
            dt = datetime.fromisoformat(generated_at)
            date_str = dt.strftime('%A, %B %d, %Y  %H:%M')
        except Exception:
            date_str = generated_at

    body = _to_html(content)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body  {{ margin:0; padding:0; background:#f0f4f8; font-family:Arial,Helvetica,sans-serif; }}
  .wrap {{ max-width:680px; margin:24px auto; background:#fff;
           border-radius:12px; overflow:hidden;
           box-shadow:0 2px 16px rgba(0,0,0,.12); }}
  .hdr  {{ background:linear-gradient(135deg,#1e3a5f,#2d6a9f);
           padding:28px 32px; color:#fff; }}
  .hdr h1 {{ margin:0; font-size:22px; letter-spacing:.4px; }}
  .hdr p  {{ margin:6px 0 0; opacity:.75; font-size:13px; }}
  .bdy  {{ padding:28px 32px; color:#333; line-height:1.75; font-size:14px; }}
  h2    {{ color:#1e3a5f; font-size:16px; border-bottom:2px solid #e8f0fb;
           padding-bottom:6px; margin-top:28px; }}
  h3    {{ color:#2d6a9f; font-size:15px; margin-top:20px; }}
  ul    {{ padding-left:22px; margin:8px 0; }}
  li    {{ margin-bottom:4px; }}
  .box-warning   {{ background:#fff8e1; border-left:4px solid #f59e0b;
                    padding:12px 16px; border-radius:0 6px 6px 0;
                    margin:16px 0; font-size:13px; color:#78350f; }}
  .box-highlight {{ background:#eff6ff; border-left:4px solid #3b82f6;
                    padding:12px 16px; border-radius:0 6px 6px 0; margin:16px 0; }}
  .box-success   {{ background:#f0fdf4; border-left:4px solid #22c55e;
                    padding:12px 16px; border-radius:0 6px 6px 0; margin:16px 0; }}
  .ftr  {{ background:#f8fafc; padding:16px 32px; text-align:center;
           font-size:12px; color:#9ca3af; border-top:1px solid #e8edf2; }}
</style>
</head>
<body>
<div class="wrap">
  <div class="hdr">
    <h1>&#x1F4CA; Daily Investor Insights</h1>
    <p>{date_str}</p>
  </div>
  <div class="bdy">
    {body}
  </div>
  <div class="ftr">
    Generated by <strong>MyAI Assist</strong> &bull; Powered by Gemini AI
    &bull; This is <em>not</em> financial advice.
  </div>
</div>
</body>
</html>"""


def send_investor_email(content, generated_at=None):
    """
    Send investor insights email to recipients configured in .env.

    Required env vars:
        EMAIL_SENDER      – sender Gmail address
        EMAIL_PASSWORD    – Gmail App Password
        EMAIL_RECIPIENTS  – comma-separated recipient addresses

    Optional env vars:
        EMAIL_SMTP_HOST   – default smtp.gmail.com
        EMAIL_SMTP_PORT   – default 587
    """
    smtp_host = os.environ.get('EMAIL_SMTP_HOST', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('EMAIL_SMTP_PORT', '587'))
    sender    = os.environ.get('EMAIL_SENDER', '').strip()
    password  = os.environ.get('EMAIL_PASSWORD', '').strip()
    recip_raw = os.environ.get('EMAIL_RECIPIENTS', '').strip()

    if not sender or not password or not recip_raw:
        msg = "Email not configured – set EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECIPIENTS in .env"
        logger.error(msg)
        return False, msg

    recipients = [r.strip() for r in recip_raw.split(',') if r.strip()]
    if not recipients:
        return False, "No valid EMAIL_RECIPIENTS found"

    today   = datetime.now().strftime('%A, %B %d, %Y')
    subject = f"\U0001f4ca Daily Investor Insights – {today}"

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From']    = f"MyAI Assist <{sender}>"
    msg['To']      = ', '.join(recipients)

    # Plain-text fallback
    msg.attach(MIMEText(f"Daily Investor Insights – {today}\n\n{content}", 'plain', 'utf-8'))
    # HTML version
    msg.attach(MIMEText(build_html_email(content, generated_at), 'html', 'utf-8'))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, recipients, msg.as_string())
        logger.info(f"Investor insights email sent to: {', '.join(recipients)}")
        return True, f"Email sent to {len(recipients)} recipient(s)"
    except smtplib.SMTPAuthenticationError:
        err = "SMTP authentication failed – check EMAIL_SENDER / EMAIL_PASSWORD"
        logger.error(err)
        return False, err
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False, str(e)
